- id: doi:10.1021/acscatal.1c02074
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/accacs/2021/accacs.2021.11.issue-15/acscatal.1c02074/20210802/images/large/cs1c02074_0012.jpeg

- id: doi:10.1002/anie.202100337
  image: https://onlinelibrary.wiley.com/cms/asset/02c3862e-2284-4c98-aea8-95db6128cd71/anie202100337-fig-0004-m.jpg

- id: doi:10.1021/acsenergylett.1c00234
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/aelccp/2021/aelccp.2021.6.issue-3/acsenergylett.1c00234/20210305/images/medium/nz1c00234_0004.gif

- id: doi:10.1021/acsanm.0c02768
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/aanmf6/2021/aanmf6.2021.4.issue-1/acsanm.0c02768/20210115/images/large/an0c02768_0008.jpeg

- id: doi:10.1021/acsaem.0c00972
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/aaemcq/2020/aaemcq.2020.3.issue-8/acsaem.0c00972/20200817/images/large/ae0c00972_0006.jpeg

- id: doi:10.1103/PhysRevApplied.14.014068
  image: https://journals.aps.org/prapplied/article/10.1103/PhysRevApplied.14.014068/figures/2/medium

- id: doi:10.1021/acs.jpclett.0c00335
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/jpclcd/2020/jpclcd.2020.11.issue-7/acs.jpclett.0c00335/20200327/images/large/jz0c00335_0006.jpeg
  extra-links:
    - type: source
      link: https://valexandrov.github.io/varg/papers/acs.jpclett.0c00335.pdf

- id: doi:10.1021/acscatal.9b05544
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/accacs/2020/accacs.2020.10.issue-6/acscatal.9b05544/20200316/images/large/cs9b05544_0011.jpeg

- id: doi:10.1002/prot.25885
  image: https://onlinelibrary.wiley.com/cms/asset/b6fbc343-8371-4cf5-b29c-05663cfb0f7c/prot25885-fig-0001-m.jpg

- id: doi:10.1021/acs.jpcc.9b07860
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/jpccck/2019/jpccck.2019.123.issue-50/acs.jpcc.9b07860/20191212/images/medium/jp9b07860_0005.gif

- id: doi:10.1021/acs.nanolett.9b03056
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/nalefd/2019/nalefd.2019.19.issue-10/acs.nanolett.9b03056/20191003/images/large/nl9b03056_0009.jpeg

- id: doi:10.1103/PhysRevApplied.12.024044
  image: https://journals.aps.org/prapplied/article/10.1103/PhysRevApplied.12.024044/figures/2/medium

- id: doi:10.1021/acs.jpcc.9b03418
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/jpccck/2019/jpccck.2019.123.issue-36/acs.jpcc.9b03418/20190905/images/large/jp-2019-03418f_0005.jpeg

- id: doi:10.1021/acsami.9b06010
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/aamick/2019/aamick.2019.11.issue-22/acsami.9b06010/20190529/images/medium/am-2019-06010u_0007.gif

- id: doi:10.1021/acs.jpcb.8b10980
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/jpcbfk/2019/jpcbfk.2019.123.issue-18/acs.jpcb.8b10980/20190506/images/medium/jp-2018-10980a_0012.gif

- id: doi:10.1021/acs.jpcc.8b09868
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/jpccck/2018/jpccck.2018.122.issue-51/acs.jpcc.8b09868/20181220/images/medium/jp-2018-09868k_0010.gif

- id: doi:10.1103/PhysRevLett.121.056601
  image: https://journals.aps.org/prl/article/10.1103/PhysRevLett.121.056601/figures/3/medium

- id: doi:10.1021/acs.jpcc.8b03743
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/jpccck/2018/jpccck.2018.122.issue-28/acs.jpcc.8b03743/20180712/images/large/jp-2018-03743r_0005.jpeg

- id: doi:10.1021/acsami.8b05864
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/aamick/2018/aamick.2018.10.issue-24/acsami.8b05864/20180614/images/medium/am-2018-05864p_0004.gif

- id: doi:10.1149/2.1251805jes
  image: 

- id: doi:10.1021/acscatal.7b04347
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/accacs/2018/accacs.2018.8.issue-5/acscatal.7b04347/20180430/images/medium/cs-2017-04347y_0009.gif

- id: doi:10.1021/acs.nanolett.7b04444
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/nalefd/2018/nalefd.2018.18.issue-1/acs.nanolett.7b04444/20180109/images/medium/nl-2017-044449_0006.gif

- id: doi:10.1016/j.jpowsour.2017.10.050
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0378775317313939-fx1.jpg

- id: doi:10.1039/C7CP02350B
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=C7CP02350B&imageInfo.ImageIdentifier.Year=2017

- id: doi:10.1021/acs.jpcc.7b02777
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/jpccck/2017/jpccck.2017.121.issue-19/acs.jpcc.7b02777/20170512/images/medium/jp-2017-02777e_0009.gif

- id: doi:10.1103/PhysRevB.95.035301
  image: https://journals.aps.org/prb/article/10.1103/PhysRevB.95.035301/figures/1/medium

- id: doi:10.1016/j.corsci.2016.10.001
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0010938X16309179-gr1.jpg

- id: doi:10.1063/1.4962748
  image: https://aip.scitation.org/na101/home/literatum/publisher/aip/journals/content/jcp/2016/jcp.2016.145.issue-11/1.4962748/production/images/medium/1.4962748.figures.f2.gif
